SET BLOSC_INSTALL_DIR=D:\Projects\DepsRoot\c-blosc\1.11.2\built

SET CMAKE_OUTPUT_DIR=compiler\vc14win64-cmake\

SET BLOSC_ROOT_DIR=%~sdp0

IF EXIST %CMAKE_OUTPUT_DIR% rmdir /S /Q %CMAKE_OUTPUT_DIR%
mkdir %CMAKE_OUTPUT_DIR%
pushd %CMAKE_OUTPUT_DIR%

cmake ^
	-D CMAKE_INSTALL_PREFIX=%BLOSC_INSTALL_DIR% ^
	-D BUILD_TESTS=OFF ^
	-D DEACTIVATE_LZ4=ON ^
	-D DEACTIVATE_ZSTD=ON ^
	-G "Visual Studio 14 2015" ^
	-Ax64 ^
	%BLOSC_ROOT_DIR%
popd
if %ERRORLEVEL% NEQ 0 exit /b %ERRORLEVEL%
